---
# Setup/install tasks.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define php_packages.
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

# Setup the server
- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

# Install owncloud on the server
- include_tasks: install-debian.yml
...